AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Accounts API (HTTP API + Lambda + DynamoDB)

Globals:
  Function:
    Runtime: nodejs20.x
    MemorySize: 256
    Timeout: 10
    Environment:
      Variables:
        TABLE_NAME: !Ref AccountsTable
        DDB_ENDPOINT: !Ref DdbEndpoint   # <-- add this
    Tracing: Active

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowMethods: ["GET", "POST", "OPTIONS"]
        AllowHeaders: ["*"]

  ListAccountsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/list.handler
      Events:
        GetAccounts:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /accounts
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints: [src/handlers/list.ts]

  CreateAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create.handler
      Events:
        PostAccount:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /accounts
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints: [src/handlers/create.ts]

  GetAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getById.handler
      Events:
        GetAccount:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /accounts/{id}
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints: [src/handlers/getById.ts]

  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Accounts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

Outputs:
  HttpApiUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Description: Deployed HTTP API URL
